# Generated by Django 4.1.2 on 2022-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ad_picture/", verbose_name="Фото"
            ),
        ),
    ]
