# Generated by Django 4.1.2 on 2022-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
    ]
