# Generated by Django 4.1.2 on 2022-10-26 12:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12, region=None, unique=True, verbose_name="Телефон"
            ),
        ),
    ]
