# Generated by Django 4.1.2 on 2022-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_picture/",
                verbose_name="Аватарка",
            ),
        ),
    ]
